default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password:
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sokoban_development

test:
  <<: *default
  database: sokoban_test

production:
  <<: *default
  database: sokoban_production
  url: <%= ENV['DATABASE_URL'] %>
